### ISSUE TITLE
Someone I broke the editor??

### ISSUE THREAD

**Issue by jemunm378** [GrooveProgramming/editor#20]
If someone could fix it. That will be nice.

**Comment by AmazingMech2418** [comment]
Um, well, since it wasn't a PR and there were a lot of commits afterwards, we can't automatically revert it. If you could manually revert the commits since the first red "x", that should fix it.

**Comment by AmazingMech2418** [comment]
Wait, did you actually upload a file to the wrong repo?

**Comment by JimmyRooster** [comment]
I can try.

**Comment by JimmyRooster** [comment]
looks like some random extra close tags.

**Comment by JimmyRooster** [comment]
You missed the close script tag at the end of the script in index.html.

**Comment by jemunm378** [comment]
That didn’t work :/

**Comment by B294** [comment]
Fixed.
